
- flicker:
- flicker:
    name: Flicker Effect With Custom Values
    alpha: 95%
    intensity: 1.5%


- strobe:
- strobe:
    name: Strobe Effect With Custom Values
    colors:
      - state: True
        brightness: 100%
        red: 100%
        green: 90%
        blue: 0%
        duration: 500ms
      - state: False
        duration: 250ms
      - state: True
        brightness: 100%
        red: 0%
        green: 100%
        blue: 0%
        duration: 500ms


- random:
- random:
    name: Slow Random Effect
    transition_length: 30s
    update_interval: 30s
- random:
    name: Fast Random Effect
    transition_length: 4s
    update_interval: 5s


- addressable_rainbow:
- addressable_rainbow:
    name: Rainbow Effect With Custom Values
    speed: 10
    width: 50


- addressable_color_wipe:
- addressable_color_wipe:
    name: Color Wipe Effect With Custom Values
    colors:
      - red: 100%
        green: 100%
        blue: 100%
        num_leds: 1
      - red: 0%
        green: 0%
        blue: 0%
        num_leds: 1
    add_led_interval: 100ms
    reverse: False


- addressable_twinkle:
- addressable_twinkle:
    name: Twinkle Effect With Custom Values
    twinkle_probability: 5%
    progress_interval: 4ms


- addressable_random_twinkle:
- addressable_random_twinkle:
    name: Random Twinkle Effect With Custom Values
    twinkle_probability: 5%
    progress_interval: 32ms


- addressable_fireworks:
- addressable_fireworks:
    name: Fireworks Effect With Custom Values
    update_interval: 32ms
    spark_probability: 10%
    use_random_color: false
    fade_out_rate: 120


- addressable_flicker:
- addressable_flicker:
    name: Addressable Flicker Effect With Custom Values
    update_interval: 16ms
    intensity: 5%


- addressable_scan:
- addressable_scan:
    name: Scan Effect With Custom Values
    move_interval: 5ms
    scan_width: 1
