substitutions:
  node_platform: esp8266
  node_board: esp01_1m

  
esphome:
  platform: esp8266
  board: esp01_1m
  board_flash_mode: dout


binary_sensor:
  - platform: gpio
    id: ${hostid}_button1
    name: ${hostname} Button 1
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True


output:
  - platform: gpio
    pin: GPIO12
    id: ${hostid}_output_relay1
