substitutions:
  hostid: office_environment
  hostname: Office Environment
  comment: Ambient sensor for office
  node_platform: esp8266
  node_board: d1_mini
  

packages:
  core: !include common/core.yaml
  basic_sensors: !include common/basic_sensors.yaml


dallas:
  - pin: D3
    update_interval: 30s

sensor:
  - platform: dht
    pin: D5
    model: DHT22_TYPE2
    temperature:
      name: ${hostname} DHT Temperature
      id: ${hostid}_dht_temperature
      filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10
    humidity:
      name: ${hostname} DHT Humidity
      id: ${hostid}_dht_humidity
      filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10
    update_interval: 30s

  - platform: dallas
    address: 0x0201201B7F562728
    name: ${hostname} Dallas Temperature
    id: ${hostid}_dallas_temperature
    filters:
    - sliding_window_moving_average:
        window_size: 10
        send_every: 2

  - platform: template
    name:  ${hostname} Temperature
    id:  ${hostid}_temperature
    force_update: true
    lambda: |-
      float sensor1 = (float)id( ${hostid}_dht_temperature ).state;
      float sensor2 = (float)id( ${hostid}_dallas_temperature ).state;
      return (float)(sensor1+sensor2)/2;
    update_interval: 30s
    unit_of_measurement: °C
    icon: mdi:thermometer