substitutions:
  hostid: dishwasher
  hostname: Dishwasher
  comment: Shelly1PM that monitores dishwasher power consumption



packages:
  core: !include common/core.yaml
  basic_sensors: !include common/basic_sensors.yaml
  device_base: !include devices/shelly1pm.yaml


esphome:
  on_boot:
    priority: 750
    then:
      - switch.turn_on: ${hostid}_switch1


switch:
  - platform: output
    name: ${hostname}
    id: ${hostid}_switch1
    output: ${hostid}_output_relay1
    internal: true
    

binary_sensor:
  - platform: template
    name: ${hostname} In Operation
    id: ${hostid}_in_operation
    lambda: return id(${hostid}_wattage1).state > 0;
    filters:
      - delayed_off: 900s