
#  openuv:
#    api_key: !secret OPENUV_API

sensor:
  - platform: template
    sensors:
      uv_low:
        friendly_name: "UV lavt"
        value_template: 3

automation:
  - alias: Opdater OpenUV halve time
    trigger:
      platform: time_pattern
      minutes: "/60"
    condition:
      condition: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      above: 10
    action:
      service: openuv.update_uv_index_data

  - alias: Opdater OpenUV beskyttelsesvindue
    trigger:
      platform: time
      at: "02:12:00"
    action:
      service: openuv.update_protection_data
