
sensor:
  - platform: template
    sensors:
      preceding_day_energy_usage:
        unit_of_measurement: "kWh"
        friendly_name: Eloverblik Energy
        unique_id: group.eloverblik_energy
        value_template: >-
          {% set hour = now().hour %}
          {% set sensor = ['sensor.eloverblik_energy', hour, hour+1] | join('_') %}
          {{ states(sensor) }}
        attribute_templates:
          metering_start: >-
            {% set hour = now().hour %}
            {% set sensor = ['sensor.eloverblik_energy', hour, hour+1] | join('_') %}
            {% set datetimestr = [state_attr(sensor, 'Metering date'),'T', hour] | join('') %}
            {{ strptime(datetimestr, '%Y-%m-%dT%H') }}
          metering_end: >-
            {% set hour = now().hour %}
            {% set sensor = ['sensor.eloverblik_energy', hour, hour+1] | join('_') %}
            {% set datetimestr = [state_attr(sensor, 'Metering date'),'T', hour, ':59', ':59'] | join('') %}
            {{ strptime(datetimestr, '%Y-%m-%dT%H:%M:%S') }}

  - platform: statistics
    name: sliding week energy sum
    entity_id: sensor.eloverblik_energy_total
    max_age:
      days: 7

  - platform: statistics
    name: sliding month energy sum
    entity_id: sensor.eloverblik_energy_total
    max_age:
      days: 28


automation:
  - alias: "Opdater Eloverblik sensor"
    id: update_eloverblik_sensor
    trigger:
      platform: time_pattern
      minutes: '/0'
    action:
      - service: homeassistant.update_entity
        entity_id: sensor.preceding_day_energy_usage
      - service: homeassistant.update_entity
        entity_id: group.eloverblik_energy
      - service: homeassistant.update_entity
        entity_id: sensor.eloverblik_energy_total


group:
  eloverblik_energy:
    entities:
      - sensor.eloverblik_energy_0_1
      - sensor.eloverblik_energy_1_2
      - sensor.eloverblik_energy_2_3
      - sensor.eloverblik_energy_3_4
      - sensor.eloverblik_energy_4_5
      - sensor.eloverblik_energy_5_6
      - sensor.eloverblik_energy_6_7
      - sensor.eloverblik_energy_7_8
      - sensor.eloverblik_energy_8_9
      - sensor.eloverblik_energy_9_10
      - sensor.eloverblik_energy_10_11
      - sensor.eloverblik_energy_11_12
      - sensor.eloverblik_energy_12_13
      - sensor.eloverblik_energy_13_14
      - sensor.eloverblik_energy_14_15
      - sensor.eloverblik_energy_15_16
      - sensor.eloverblik_energy_16_17
      - sensor.eloverblik_energy_17_18
      - sensor.eloverblik_energy_18_19
      - sensor.eloverblik_energy_19_20
      - sensor.eloverblik_energy_20_21
      - sensor.eloverblik_energy_21_22
      - sensor.eloverblik_energy_22_23
      - sensor.eloverblik_energy_23_24
